//! The persistent KPS identity and the addresses published for it.
//!
//! The certhash is the stable half of the node's KPS address
//! (`<ip>:<port>:<certhash>`): it is derived from the key file, so the file
//! lives on a persistent volume and is never regenerated by accident. The
//! private key is never logged or printed; only the certhash is.

use std::net::{IpAddr, SocketAddr, UdpSocket};
use std::path::Path;

use tracing::warn;

use crate::error::IdentityError;

/// Outcome of [`load_or_create`].
pub struct LoadedIdentity {
    pub identity: kps::Identity,
    /// The key file did not exist and was generated now.
    pub created: bool,
}

/// Loads the identity at `path`, creating the key (mode 0600) and its parent
/// directory (mode 0700) on first use.
pub fn load_or_create(path: &Path) -> Result<LoadedIdentity, IdentityError> {
    if let Some(parent) = path.parent().filter(|p| !p.as_os_str().is_empty()) {
        if !parent.exists() {
            create_private_dir(parent)?;
        }
    }
    let existed = path.exists();
    let identity =
        kps::Identity::load_or_create(path).map_err(|source| IdentityError::LoadOrCreate {
            path: path.to_path_buf(),
            source,
        })?;
    if existed {
        warn_if_readable_by_others(path);
    }
    Ok(LoadedIdentity {
        identity,
        created: !existed,
    })
}

/// Reads an existing identity without creating one (`check-config`).
pub fn read_existing(path: &Path) -> Result<Option<kps::Identity>, IdentityError> {
    let pem = match std::fs::read_to_string(path) {
        Ok(pem) => pem,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(None),
        Err(source) => {
            return Err(IdentityError::Read {
                path: path.to_path_buf(),
                source,
            })
        }
    };
    kps::Identity::from_pem(&pem)
        .map(Some)
        .map_err(|source| IdentityError::Parse {
            path: path.to_path_buf(),
            source,
        })
}

#[cfg(unix)]
fn create_private_dir(dir: &Path) -> Result<(), IdentityError> {
    use std::os::unix::fs::DirBuilderExt;
    std::fs::DirBuilder::new()
        .recursive(true)
        .mode(0o700)
        .create(dir)
        .map_err(|source| IdentityError::CreateDir {
            path: dir.to_path_buf(),
            source,
        })
}

#[cfg(not(unix))]
fn create_private_dir(dir: &Path) -> Result<(), IdentityError> {
    std::fs::create_dir_all(dir).map_err(|source| IdentityError::CreateDir {
        path: dir.to_path_buf(),
        source,
    })
}

#[cfg(unix)]
fn warn_if_readable_by_others(path: &Path) {
    use std::os::unix::fs::PermissionsExt;
    if let Ok(meta) = std::fs::metadata(path) {
        let mode = meta.permissions().mode() & 0o777;
        if mode & 0o077 != 0 {
            warn!(
                file = %path.display(),
                mode = format!("{mode:o}"),
                "KPS identity key is readable by other users; run chmod 600 on it"
            );
        }
    }
}

#[cfg(not(unix))]
fn warn_if_readable_by_others(_path: &Path) {}

/// Formats `ip:port:certhash`, bracketing IPv6 (KPS SPEC §2).
#[must_use]
pub fn format_address(ip: IpAddr, port: u16, certhash: &str) -> String {
    kps::format_address(&ip.to_string(), port, certhash)
}

/// The IPs to advertise and whether they were detected rather than configured.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AdvertisedIps {
    pub ips: Vec<IpAddr>,
    pub detected: bool,
}

/// Configured public IPs, or the outbound source addresses of this host when
/// none are configured (IPv4, and IPv6 when routable). Falls back to the bind
/// address, then to loopback.
#[must_use]
pub fn advertised_ips(configured: &[IpAddr], bind: SocketAddr) -> AdvertisedIps {
    if !configured.is_empty() {
        return AdvertisedIps {
            ips: configured.to_vec(),
            detected: false,
        };
    }
    let mut ips = Vec::new();
    if bind.ip().is_unspecified() {
        if let Some(ip) = detect_source_ip(false) {
            ips.push(ip);
        }
        if bind.is_ipv6() {
            if let Some(ip) = detect_source_ip(true) {
                ips.push(ip);
            }
        }
    } else {
        ips.push(bind.ip().to_canonical());
    }
    if ips.is_empty() {
        ips.push(IpAddr::from([127, 0, 0, 1]));
    }
    AdvertisedIps {
        ips,
        detected: true,
    }
}

/// The local address the OS would use to reach the internet in one family.
/// A UDP `connect` selects the route without sending a packet.
#[must_use]
pub fn detect_source_ip(v6: bool) -> Option<IpAddr> {
    let (bind, probe) = if v6 {
        ("[::]:0", "[2001:4860:4860::8888]:53")
    } else {
        ("0.0.0.0:0", "8.8.8.8:53")
    };
    let sock = UdpSocket::bind(bind).ok()?;
    sock.connect(probe).ok()?;
    let ip = sock.local_addr().ok()?.ip();
    (!ip.is_loopback() && !ip.is_unspecified()).then_some(ip)
}

/// Not reachable from the public internet: private, shared (CGNAT),
/// loopback, link-local or unique-local.
#[must_use]
pub fn is_non_public(ip: IpAddr) -> bool {
    match ip.to_canonical() {
        IpAddr::V4(v4) => {
            let o = v4.octets();
            v4.is_private()
                || v4.is_loopback()
                || v4.is_link_local()
                || v4.is_unspecified()
                || (o[0] == 100 && (o[1] & 0xc0) == 64)
        }
        IpAddr::V6(v6) => {
            let s = v6.segments();
            v6.is_loopback()
                || v6.is_unspecified()
                || (s[0] & 0xfe00) == 0xfc00
                || (s[0] & 0xffc0) == 0xfe80
        }
    }
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used, clippy::expect_used)]

    use super::*;

    #[test]
    fn creates_once_then_reloads_the_same_certhash() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("nested").join("kps.key");
        let first = load_or_create(&path).unwrap();
        assert!(first.created);
        let second = load_or_create(&path).unwrap();
        assert!(!second.created);
        assert_eq!(first.identity.certhash, second.identity.certhash);
        let read = read_existing(&path).unwrap().unwrap();
        assert_eq!(read.certhash, first.identity.certhash);
        assert!(first.identity.certhash.starts_with("uEi"));
    }

    #[cfg(unix)]
    #[test]
    fn key_file_and_directory_are_private() {
        use std::os::unix::fs::PermissionsExt;
        let dir = tempfile::tempdir().unwrap();
        let parent = dir.path().join("id");
        let path = parent.join("kps.key");
        load_or_create(&path).unwrap();
        let file_mode = std::fs::metadata(&path).unwrap().permissions().mode() & 0o777;
        let dir_mode = std::fs::metadata(&parent).unwrap().permissions().mode() & 0o777;
        assert_eq!(file_mode, 0o600);
        assert_eq!(dir_mode, 0o700);
    }

    #[test]
    fn read_existing_does_not_create() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("kps.key");
        assert!(read_existing(&path).unwrap().is_none());
        assert!(!path.exists());
        std::fs::write(&path, "not a pem").unwrap();
        assert!(matches!(
            read_existing(&path),
            Err(IdentityError::Parse { .. })
        ));
    }

    #[test]
    fn addresses_bracket_ipv6() {
        assert_eq!(
            format_address("203.0.113.5".parse().unwrap(), 15005, "uEiX"),
            "203.0.113.5:15005:uEiX"
        );
        assert_eq!(
            format_address("2001:db8::7".parse().unwrap(), 15005, "uEiX"),
            "[2001:db8::7]:15005:uEiX"
        );
    }

    #[test]
    fn configured_ips_win_over_detection() {
        let ip: IpAddr = "203.0.113.5".parse().unwrap();
        let adv = advertised_ips(&[ip], "[::]:15005".parse().unwrap());
        assert_eq!(adv.ips, vec![ip]);
        assert!(!adv.detected);
        let adv = advertised_ips(&[], "127.0.0.1:15005".parse().unwrap());
        assert_eq!(adv.ips, vec!["127.0.0.1".parse::<IpAddr>().unwrap()]);
        assert!(adv.detected);
    }

    #[test]
    fn classifies_non_public_addresses() {
        for ip in [
            "10.1.2.3",
            "172.31.66.207",
            "192.168.1.1",
            "100.64.0.1",
            "127.0.0.1",
            "169.254.1.1",
            "::1",
            "fd00::1",
            "fe80::1",
            "::ffff:10.0.0.1",
        ] {
            assert!(is_non_public(ip.parse().unwrap()), "{ip}");
        }
        for ip in [
            "3.236.170.102",
            "203.0.113.5",
            "2600:1f18::1",
            "100.128.0.1",
        ] {
            assert!(!is_non_public(ip.parse().unwrap()), "{ip}");
        }
    }
}
