//! The KPS listener, connection admission, per-connection stream handling,
//! background tasks and graceful shutdown.
//!
//! Lifecycle of a connection:
//! 1. `kps::Listener::accept` yields an authenticated, established connection
//!    (WebRTC or QUIC; the API does not say which).
//! 2. The global and per-IP caps admit it or close it with `queue-full`.
//! 3. Each accepted stream is one HTTP/1.1 exchange ([`crate::exchange`]);
//!    beyond `max_streams_per_connection` concurrent streams, new streams are
//!    reset with `queue-full`.
//! 4. The connection is closed when the peer leaves, after
//!    `connection_idle_timeout_ms` without streams, or at shutdown once its
//!    in-flight exchanges finish (bounded by the grace period).

use std::net::{IpAddr, SocketAddr};
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::{Arc, Mutex, PoisonError};
use std::time::{Duration, Instant};

use kps::ErrorCode;
use tokio::sync::{OwnedSemaphorePermit, Semaphore};
use tokio::task::JoinHandle;
use tokio_util::sync::CancellationToken;
use tokio_util::task::TaskTracker;
use tracing::{debug, info, warn};

use crate::app::{metadata_document, App, Router};
use crate::bundles::{log_report, BundleStore};
use crate::config::Settings;
use crate::error::StartError;
use crate::exchange::{serve_stream, StreamOutcome};
use crate::identity::{self, advertised_ips, format_address, is_non_public};
use crate::limits::ConnLimiter;
use crate::metrics::{self, HealthInfo, Metrics};
use crate::proxy::UpstreamClient;

/// A started server. Dropping it does not stop it; call
/// [`RunningServer::shutdown`] and then [`RunningServer::wait`].
#[derive(Debug)]
pub struct RunningServer {
    certhash: String,
    port: u16,
    addresses: Vec<String>,
    addresses_detected: bool,
    identity_created: bool,
    metrics_addr: Option<SocketAddr>,
    shutdown: CancellationToken,
    health: Arc<HealthInfo>,
    metrics: Arc<Metrics>,
    tasks: Vec<JoinHandle<()>>,
}

impl RunningServer {
    /// The certhash clients pin (stable for a given key file).
    #[must_use]
    pub fn certhash(&self) -> &str {
        &self.certhash
    }

    /// The UDP port the listener bound.
    #[must_use]
    pub fn port(&self) -> u16 {
        self.port
    }

    /// The published `ip:port:certhash` addresses.
    #[must_use]
    pub fn addresses(&self) -> &[String] {
        &self.addresses
    }

    /// `true` when the advertised IPs were detected rather than configured.
    #[must_use]
    pub fn addresses_detected(&self) -> bool {
        self.addresses_detected
    }

    /// `true` when the identity key was generated by this start.
    #[must_use]
    pub fn identity_created(&self) -> bool {
        self.identity_created
    }

    /// The address to dial on this host (loopback), for tests and tooling.
    #[must_use]
    pub fn local_address(&self) -> String {
        format_address(IpAddr::from([127, 0, 0, 1]), self.port, &self.certhash)
    }

    /// Where `/metrics` and `/health` are served, when enabled.
    #[must_use]
    pub fn metrics_addr(&self) -> Option<SocketAddr> {
        self.metrics_addr
    }

    #[must_use]
    pub fn metrics(&self) -> &Arc<Metrics> {
        &self.metrics
    }

    /// Starts a graceful shutdown: no new connections or streams, in-flight
    /// exchanges get the grace period, then every connection is closed.
    pub fn shutdown(&self) {
        self.health.shutting_down.store(true, Ordering::Relaxed);
        self.shutdown.cancel();
    }

    /// A token that triggers [`RunningServer::shutdown`] when cancelled.
    #[must_use]
    pub fn shutdown_token(&self) -> CancellationToken {
        self.shutdown.clone()
    }

    /// Waits for every server task to finish (after a shutdown).
    pub async fn wait(self) {
        for task in self.tasks {
            if let Err(e) = task.await {
                warn!(error = %e, "server task ended abnormally");
            }
        }
    }
}

/// Binds the KPS listener (and the metrics endpoint), loads the identity and
/// bundles, and starts serving.
pub async fn start(settings: Settings) -> Result<RunningServer, StartError> {
    let settings = Arc::new(settings);
    let metrics = Metrics::new();

    let loaded = identity::load_or_create(&settings.identity_key_file)?;
    if loaded.created {
        info!(
            file = %settings.identity_key_file.display(),
            certhash = %loaded.identity.certhash,
            "generated a new KPS identity key; back it up with the node's secrets"
        );
    }
    let identity_created = loaded.created;
    let certhash = loaded.identity.certhash.clone();

    let bundles = match &settings.bundles {
        None => None,
        Some(bundle_settings) => {
            let (store, report) = BundleStore::load(bundle_settings.clone())?;
            log_report(&report, &bundle_settings.dir);
            info!(
                dir = %bundle_settings.dir.display(),
                loaded = store.len(),
                "worker bundle resolver enabled"
            );
            metrics.bundles_loaded.set(store.len() as i64);
            Some(Arc::new(store))
        }
    };

    let listener = kps::listen(
        &settings.listen.to_string(),
        kps::ListenOptions {
            identity: Some(loaded.identity),
            key_file: None,
        },
    )
    .await
    .map_err(|source| StartError::Listen {
        addr: settings.listen,
        source,
    })?;
    let port = listener.port();

    let advertised = advertised_ips(&settings.public_ips, settings.listen);
    let addresses: Vec<String> = advertised
        .ips
        .iter()
        .map(|ip| format_address(*ip, port, &certhash))
        .collect();
    if advertised.detected {
        warn!(
            "kps.public_ips is not set; advertising detected addresses. Behind NAT (including EC2) set NOX_KPS__KPS__PUBLIC_IPS to the public IP"
        );
    }
    for ip in advertised.ips.iter().filter(|ip| is_non_public(**ip)) {
        warn!(ip = %ip, "advertised IP is not publicly routable; remote clients cannot dial it");
    }

    let metrics_listener = match settings.metrics_listen {
        None => None,
        Some(addr) => Some(
            tokio::net::TcpListener::bind(addr)
                .await
                .map_err(|source| StartError::MetricsBind { addr, source })?,
        ),
    };
    let metrics_addr = metrics_listener.as_ref().and_then(|l| l.local_addr().ok());

    let app = Arc::new(App {
        router: Router::new(settings.routes.clone()),
        upstream: UpstreamClient::new(settings.proxy.clone()),
        metadata_json: metadata_document(&settings.routes, bundles.is_some(), &addresses),
        bundles: bundles.clone(),
        metrics: Arc::clone(&metrics),
        inflight: Arc::new(Semaphore::new(settings.proxy.max_inflight)),
        conn_limiter: ConnLimiter::new(
            settings.limits.max_connections,
            settings.limits.max_connections_per_ip,
            settings.limits.ipv6_prefix_len,
        ),
        settings: Arc::clone(&settings),
    });

    let shutdown = CancellationToken::new();
    let health = Arc::new(HealthInfo {
        certhash: certhash.clone(),
        addresses: addresses.clone(),
        shutting_down: AtomicBool::new(false),
    });

    let mut tasks = Vec::new();
    tasks.push(tokio::spawn(accept_loop(
        listener,
        Arc::clone(&app),
        shutdown.clone(),
    )));
    if let Some(listener) = metrics_listener {
        tasks.push(tokio::spawn(metrics::serve(
            listener,
            Arc::clone(&metrics),
            Arc::clone(&health),
            shutdown.clone(),
        )));
    }
    if let (Some(store), Some(interval)) = (
        bundles,
        settings.bundles.as_ref().and_then(|b| b.rescan_interval),
    ) {
        tasks.push(tokio::spawn(rescan_loop(
            store,
            interval,
            Arc::clone(&metrics),
            shutdown.clone(),
        )));
    }

    Ok(RunningServer {
        certhash,
        port,
        addresses,
        addresses_detected: advertised.detected,
        identity_created,
        metrics_addr,
        shutdown,
        health,
        metrics,
        tasks,
    })
}

async fn accept_loop(listener: kps::Listener, app: Arc<App>, shutdown: CancellationToken) {
    let tracker = TaskTracker::new();
    loop {
        tokio::select! {
            biased;
            () = shutdown.cancelled() => break,
            accepted = listener.accept() => match accepted {
                Ok(conn) => {
                    tracker.spawn(handle_conn(conn, Arc::clone(&app), shutdown.clone(), tracker.clone()));
                }
                Err(e) => {
                    warn!(error = %e, "KPS listener stopped accepting connections");
                    break;
                }
            }
        }
    }
    tracker.close();
    let grace = app.settings.shutdown_grace;
    if tokio::time::timeout(grace, tracker.wait()).await.is_err() {
        warn!(
            tasks = tracker.len(),
            grace_ms = grace.as_millis() as u64,
            "shutdown grace period elapsed with exchanges in flight; closing them"
        );
    }
    listener.close().await;
    info!("KPS listener closed");
}

/// Last time a stream was accepted or finished on a connection.
#[derive(Debug)]
struct Activity(Mutex<Instant>);

impl Activity {
    fn touch(&self) {
        *self.0.lock().unwrap_or_else(PoisonError::into_inner) = Instant::now();
    }

    fn last(&self) -> Instant {
        *self.0.lock().unwrap_or_else(PoisonError::into_inner)
    }
}

/// Why a connection was closed (metric label).
#[derive(Debug, Clone, Copy)]
enum CloseReason {
    Peer,
    Idle,
    Shutdown,
}

impl CloseReason {
    fn label(self) -> &'static str {
        match self {
            Self::Peer => "peer",
            Self::Idle => "idle",
            Self::Shutdown => "shutdown",
        }
    }
}

async fn handle_conn(
    conn: Box<dyn kps::Conn>,
    app: Arc<App>,
    shutdown: CancellationToken,
    tracker: TaskTracker,
) {
    let client_ip = conn.remote_addr().ip().to_canonical();
    let permit = match app.conn_limiter.try_admit(client_ip) {
        Ok(permit) => permit,
        Err(reason) => {
            Metrics::reason(&app.metrics.connections_rejected, reason.label());
            debug!(reason = reason.label(), "KPS connection refused");
            let _ = conn.close_with_error(ErrorCode::QueueFull).await;
            return;
        }
    };
    app.metrics.connections_accepted.inc();
    app.metrics.connections_active.inc();

    let limits = &app.settings.limits;
    let max_streams = limits.max_streams_per_connection;
    let slots = Arc::new(Semaphore::new(max_streams));
    let activity = Arc::new(Activity(Mutex::new(Instant::now())));
    let idle_timeout = limits.connection_idle_timeout;

    let reason = loop {
        let busy = slots.available_permits() < max_streams;
        let idle_at = if busy {
            Instant::now() + idle_timeout
        } else {
            activity.last() + idle_timeout
        };
        tokio::select! {
            biased;
            () = shutdown.cancelled() => break CloseReason::Shutdown,
            accepted = conn.accept_stream() => match accepted {
                Ok(stream) => {
                    activity.touch();
                    if let Ok(slot) = Arc::clone(&slots).try_acquire_owned() {
                        tracker.spawn(run_stream(stream, Arc::clone(&app), client_ip, slot, Arc::clone(&activity)));
                    } else {
                        Metrics::reason(&app.metrics.streams_rejected, "per_connection_limit");
                        tracker.spawn(async move {
                            let mut stream = stream;
                            let _ = stream.close_with_error(ErrorCode::QueueFull).await;
                        });
                    }
                }
                Err(_) => break CloseReason::Peer,
            },
            () = tokio::time::sleep_until(idle_at.into()) => {
                let idle = slots.available_permits() == max_streams
                    && activity.last().elapsed() >= idle_timeout;
                if idle {
                    break CloseReason::Idle;
                }
            }
        }
    };

    // Let in-flight exchanges on this connection finish before closing it.
    // At shutdown the accept loop bounds the whole drain by the grace period.
    let drain = Arc::clone(&slots).acquire_many_owned(max_streams as u32);
    let drain_limit = match reason {
        CloseReason::Shutdown => app.settings.shutdown_grace,
        CloseReason::Peer | CloseReason::Idle => limits.stream_timeout,
    };
    let _ = tokio::time::timeout(drain_limit, drain).await;
    if matches!(reason, CloseReason::Shutdown) {
        // A KPS close is immediate (QUIC CONNECTION_CLOSE, WebRTC teardown) and
        // drops data the client has not acknowledged yet. Give the final
        // responses time to land, or until the client closes first.
        let _ = tokio::time::timeout(app.settings.shutdown_linger, conn.closed()).await;
    }

    let _ = match reason {
        CloseReason::Idle => conn.close_with_error(ErrorCode::Timeout).await,
        CloseReason::Peer | CloseReason::Shutdown => conn.close().await,
    };
    Metrics::reason(&app.metrics.connections_closed, reason.label());
    app.metrics.connections_active.dec();
    drop(permit);
}

async fn run_stream(
    stream: Box<dyn kps::Stream>,
    app: Arc<App>,
    client_ip: IpAddr,
    slot: OwnedSemaphorePermit,
    activity: Arc<Activity>,
) {
    app.metrics.streams_accepted.inc();
    app.metrics.streams_active.inc();
    let outcome = serve_stream(stream, Arc::clone(&app), client_ip).await;
    if outcome != StreamOutcome::Completed {
        Metrics::reason(&app.metrics.stream_failures, outcome.label());
    }
    app.metrics.streams_active.dec();
    activity.touch();
    drop(slot);
}

async fn rescan_loop(
    store: Arc<BundleStore>,
    interval: Duration,
    metrics: Arc<Metrics>,
    shutdown: CancellationToken,
) {
    let mut ticker = tokio::time::interval_at(tokio::time::Instant::now() + interval, interval);
    ticker.set_missed_tick_behavior(tokio::time::MissedTickBehavior::Delay);
    loop {
        tokio::select! {
            biased;
            () = shutdown.cancelled() => return,
            _ = ticker.tick() => {
                let scan_store = Arc::clone(&store);
                match tokio::task::spawn_blocking(move || scan_store.rescan()).await {
                    Ok(Ok(report)) => {
                        log_report(&report, &store.settings().dir);
                        metrics.bundles_loaded.set(store.len() as i64);
                    }
                    Ok(Err(e)) => warn!(error = %e, "worker bundle rescan failed; serving the previous index"),
                    Err(e) => warn!(error = %e, "worker bundle rescan task failed; serving the previous index"),
                }
            }
        }
    }
}
