[package]
name = "nox-test-infra"
version.workspace = true
edition = "2021"
rust-version = "1.95"
authors = ["Hisoka IO"]
description = "Test infrastructure for NOX: contract deployment, virtual nodes, test harness, simulation"
license = "Apache-2.0"
repository = "https://github.com/hisoka-io/nox"
publish = false

[dependencies]
ethers = { workspace = true }
serde = { workspace = true }

[lints]
workspace = true
